name: PickleShop
version: 1.0.0
main: pl.pickleshop.PickleShop
api-version: '1.21'
author: PickleShop
description: Pickle Shop - sklep i bank Sea Pickle

commands:
  pickle:
    description: Komenda PickleShop
    usage: /pickle <balance|give>
    permission: pickleshop.use

permissions:
  pickleshop.use:
    description: Pozwala korzystac z PickleShop
    default: true
