name: PickleShop
version: 1.0.0
main: pl.pickleshop.PickleShop
api-version: '1.21'
author: PickleShop
description: Pickle Shop - sklep i bank Sea Pickle

commands:
  sklep:
    description: Otwiera PickleShop
    aliases:
      - shop
      - pickleshop

  bank:
    description: Otwiera Pickle Bank
    aliases:
      - picklebank

  saldo:
    description: Pokazuje saldo Pickle Bank
permissions:
  pickleshop.use:
    description: Pozwala korzystac z PickleShop
    default: true
